Repository piskorzm/SpaceZ3000, pull requests merged in 2020-05, with the labels that each got.

#34 Added player abilities
  Assets/Controls.inputactions
  Assets/Controls.inputactions.meta
  Assets/Prefab/Misc/HaloPrefab.prefab
  Assets/Prefab/Misc/HaloPrefab.prefab.meta
  Assets/Prefab/Misc/MissilePrefab.prefab
  Assets/Prefab/Misc/MissilePrefab.prefab.meta
  Assets/Scenes/Demos/ShieldHealthDemo.unity
  Assets/Scripts/ChangeSize.cs
  Assets/Scripts/ChangeSize.cs.meta
  Assets/Scripts/Enemy.cs
  Assets/Scripts/Missile.cs
  Assets/Scripts/Missile.cs.meta
  Assets/Scripts/PlayerAbilitiesController.cs
  Assets/Scripts/PlayerAbilitiesController.cs.meta
  Assets/Scripts/PlayerInput.cs
  Assets/circulo.png
  Assets/circulo.png.meta
Labels: enhancement

#36 Fixed missile bug
  Assets/Scenes/Demos/ShieldHealthDemo.unity
  Assets/Scripts/Missile.cs
  Assets/circulo.png.meta
  ProjectSettings/TagManager.asset
Labels: bug

#38 God please make it fix :O
  Assets/Controls.inputactions
  Assets/Kamikaze.cs
  Assets/Kamikaze.cs.meta
  Assets/Prefab/Enemies/Kamikaze.prefab
  Assets/Prefab/Enemies/Kamikaze.prefab.meta
  Assets/Resources/circulo.png
  Assets/Resources/circulo.png.meta
  Assets/Scenes/Demos/ShieldHealthDemo.unity
  Assets/Scripts/ChangeSize.cs
  Assets/Scripts/PlayerAbilitiesController.cs
  Assets/Scripts/PlayerInput.cs
Labels: bug

#43 Camera follow player
  .gitignore
  Assets/Prefab/Misc/CM vcam1.prefab
  Assets/Prefab/Misc/CM vcam1.prefab.meta
  Assets/Scenes/Demos/ShieldHealthDemo.unity
  Assets/Scripts/EnemyHealer.cs.meta
  Assets/Scripts/EnemyHealthAdder.cs.meta
  Packages/manifest.json
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#48 New Missile behavior, trail effect added.
  Assets/Materials/trail.mat
  Assets/Materials/trail.mat.meta
  Assets/Prefab/Misc/HaloPrefab.prefab
  Assets/Prefab/Player/PlayerShield.asset
  Assets/Scenes/Demos/ShieldHealthDemo.unity
  Assets/Scripts/ChangeSize.cs
  Assets/Scripts/Missile1.cs
  Assets/Scripts/Missile1.cs.meta
  Assets/missiles.prefab
  Assets/missiles.prefab.meta
  Assets/playerShip3_red.prefab
  Assets/playerShip3_red.prefab.meta
  Packages/manifest.json
  ProjectSettings/InputManager.asset
  ProjectSettings/TagManager.asset
Labels: bug, enhancement

#60 Added URP to the project.
  Assets/Materials/2D Renderer DataMain.asset
  Assets/Materials/2D Renderer DataMain.asset.meta
  Assets/Materials/Basic Volume Profile Post Process.asset
  Assets/Materials/Basic Volume Profile Post Process.asset.meta
  Assets/Materials/HealthBar.shadergraph
  Assets/Materials/HealthBar.shadergraph.meta
  Assets/Materials/HealthbarMaterial.mat
  Assets/Materials/HealthbarShader.shader
  Assets/Materials/HealthbarShader.shader.meta
  Assets/Materials/PostProcessing.prefab
  Assets/Materials/PostProcessing.prefab.meta
  Assets/Materials/Shader Graphs_HealthBar.mat
  Assets/Materials/Shader Graphs_HealthBar.mat.meta
  Assets/Materials/UniversalRenderPipelineAssetMain.asset
  Assets/Materials/UniversalRenderPipelineAssetMain.asset.meta
  Assets/Materials/UniversalRenderPipelineAssetMain_Renderer.asset
  Assets/Materials/UniversalRenderPipelineAssetMain_Renderer.asset.meta
  Assets/Prefab/Bars/HealthBar.prefab
  Assets/Prefab/Misciles/HaloPrefab.prefab
  Assets/Prefab/ParticlEffects/EnemyDeath1.prefab
  Assets/Prefab/ParticlEffects/EnemyDeath1.prefab.meta
  Assets/Prefab/ParticlEffects/EnemyDeath2.prefab
  Assets/Prefab/ParticlEffects/EnemyDeath2.prefab.meta
  Assets/Prefab/ParticlEffects/FlareEffect.prefab
  Assets/Prefab/ParticlEffects/bluexplo.prefab
  Assets/Prefab/ParticlEffects/explosion.prefab
  Assets/Scenes/Sandbox/BasicScene.unity
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/QualitySettings.asset
Labels: enhancement

#73 Changed background star animation to use shader.
  Assets/Materials/Shader Graphs_StarShimmer.mat
  Assets/Materials/Shader Graphs_StarShimmer.mat.meta
  Assets/Materials/StarShimmer.shadergraph
  Assets/Materials/StarShimmer.shadergraph.meta
  Assets/Prefab/Drops/HealDrop.prefab
  Assets/Prefab/Environment/Main Camera.prefab
  Assets/Resources/Spritesheet/StarSpriteMap.png.meta
  Assets/Resources/Star.prefab
  Assets/Scenes/MainDemo.unity
  Assets/Scenes/Sandbox/BasicScene.unity
  Assets/Scripts/Environment/StarGenerator.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: bug, enhancement
